database: # Informations de connexion à la BDD
  host: "localhost"
  name: "book-n-go"
  user: "root"
  pass: ""

website: # Informations sur le site
  title: "Book'n'Go"
  version: "2.5"
  description: "Book'n'Go : application de carnets de voyage"
  lang: "fr"