database: # Informations de connexion à la BDD
  host: "lakartxela.iutbayonne.univ-pau.fr"
  name: "gdbelascain_pro"
  user: "gdbelascain_pro"
  pass: "gdbelascain_pro"

website: # Informations sur le site
  title: "Book'n'Go"
  version: "2.5"
  description: "Book'n'Go : application de carnets de voyage"
  lang: "fr"